baseurl      = "localhost"
title        = "Postrausch"
languageCode = "de-de"
theme        = "hello-friend-ng"
paginate     = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My own Mail Server"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My own Mail Server"
  keywords = "homepage, Mailserver"
  images = [""]
  
  enableThemeToggle = true

  [params.footer]
    trademark = true
    rss = true
  bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/DNS-HRA\">DNS-HRA</a>",
      "<a href=\"https://www.postrausch.de/datenschutzerklaerung/\">Datenschutzerklärung</a>",
      "<a href=\"https://www.postrausch.de/impressum/\">Impressum</a>"
    ]

[taxonomies]
    category = "mail"
    tag      = "mail"
    series   = "mail"

[languages]
  [languages.en]
    title = "Postrausch"
    subtitle = "My own private Mail Server"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Postrausch.tech"
      logoHomeLink = "/"
    # or
    #
    #path = "/img/postrausch.png"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "AbuseIPDB"
    name = "AbuseIPDB"
    url = "/AbuseIPDB"
